enabled_locales: ["en", "ja"]
size:
  length_name_category: 100
  length_name: 255
  length_name_description: 2000
  size_image: [80, 100]
  size_page: 8
  size_page_admin: 8
  limit: 10
  picture_size: 5
  min_quantity: 1
  min_price: 0
  min_hot: 1
  max_hot: 10
  count_new: 3
  count_hot: 3
  min_password: 6
  max_fullname: 50
  max_address: 255
  max_phone: 15
  max_quantity: 11
  max_email: 200
  status: 0
  status_number: 1
  list_image: 3
  price_begin: 0
  price_end: 0
  price_end_one: 500000
  price_begin_two: 500000
  price_end_two: 2000000
  price_begin_three: 2000000
  price_end_three: 5000000
  price_begin_four: 5000000
  price_end_four: 10000000
  price_begin_five: 10000000
  price_end_file: 500000000
  price_total_start: 0
  size_page_order: 3
account_type:
  admin: "admin"
curr_unit:
  price: USD
reload_page: "location.reload()"
value_price:
  one: "1"
  two: "2"
  three: "3"
  four: "4"
  five: "5"
time:
  time_send_email: 20
order:
  total: 0
